title: "Edoardo Paolini"
author: "Edoardo Paolini"
email: "edoardo.paolini@example.com"
description: >-
  Personal academic portfolio for Edoardo Paolini, researcher in Computer Science, Biology, and Neuroscience.
url: "https://edoardopaolini.github.io"
# theme: "" # Custom design
